# Generated by Django 2.0.3 on 2018-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_device_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('flag', models.CharField(default='STAND BY', max_length=50)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
