# Generated by Django 2.0.3 on 2018-05-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heart.Command'),
        ),
        migrations.AddField(
            model_name='status',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heart.Device'),
        ),
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
