# Generated by Django 2.0.3 on 2018-05-03 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0006_device_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='device',
        ),
        migrations.AlterField(
            model_name='device',
            name='default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heart.Command'),
        ),
    ]
