# Generated by Django 2.0.3 on 2018-05-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
