# Generated by Django 2.0.5 on 2018-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0016_auto_20180506_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.CharField(default='80', max_length=5),
        ),
    ]
