# Generated by Django 2.0.3 on 2018-05-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_auto_20180502_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='note',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
