# Generated by Django 2.0.3 on 2018-05-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0005_auto_20180502_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='default',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
