# Generated by Django 2.0.3 on 2018-05-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0007_auto_20180503_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('rpn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heart.Command')),
            ],
        ),
    ]
