# Generated by Django 2.0.3 on 2018-05-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0009_rule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
