# Generated by Django 2.0.3 on 2018-05-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0014_default_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default',
            name='name',
            field=models.CharField(default='物件', max_length=20),
        ),
    ]
