# Generated by Django 2.0.3 on 2018-05-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0015_auto_20180503_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=15),
        ),
    ]
