# Generated by Django 2.0.5 on 2018-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0018_auto_20180510_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
