# Generated by Django 2.0.5 on 2018-05-11 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0019_rule_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_step_device', to='heart.Device'),
        ),
    ]
