# Generated by Django 2.0.5 on 2018-05-17 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0020_rule_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_restrict_command', to='heart.Command')),
                ('prerequisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='heart.Command')),
            ],
        ),
    ]
