# Generated by Django 2.0.5 on 2018-05-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0021_restrict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='default',
            old_name='coommand',
            new_name='default_status',
        ),
        migrations.RemoveField(
            model_name='default',
            name='name',
        ),
    ]
