# Generated by Django 2.0.5 on 2018-05-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0023_auto_20180517_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='standBy',
            field=models.BooleanField(default=False),
        ),
    ]
